apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 53589
  publicScheme: http

insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

database:
  host: postgres
  port: 5432
  name: book_cover_designer
  user: postgres
  password: ZRnHSYxQVBAYjCIf8gBi_FLOMw0VUxyf

redis:
  enabled: true
  host: redis
  port: 6379
  password: 0oZO-B0tv6Cyn8gXMm3tH2ZQV95RF8Q9

maxRequestSize: 524288

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text
