name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - book_cover_designer_client
  - book_cover_designer_server
  - book_cover_designer_flutter
dependency_overrides:
  flutter_secure_storage: ^10.0.0
dependencies:
  flex_color_picker: ^3.7.1

